# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An Gèidheal Ùr
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A' toirt thugaibh na naidheachdan LGDTCEN+ as ùire
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://angeidhealur.scot" # the base hostname & protocol for your site

#sidebar
default-image: # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Crìstean MacMhìcheil

copyright:
   name: An Gèidheal Ùr
   link: 'https://angeidhealur.scot/'

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 12
paginate_path: /duilleag-:num/

# Tracker
analytics: 

# Comments
disqus: no
disqus-shortname: 

#social
facebook: 
instagram: https://www.instagram.com/angeidhealur
twitter: https://www.twitter.com/angeidhealur
email: chris@macmhicheil.scot

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

collections:
  events:
    output: true
    permalink: /tachartasan/:path/
    title: Tachartasan
    
months:
    - Am Faoilleach
    - An Gearran
    - Am Màrt
    - An Giblean
    - An Cèitean
    - An t-Ògmhios
    - An t-Iuchar
    - An Lùnastal
    - An t-Sultain
    - An Dàmhair
    - An t-Samhain
    - An Dùbhlachd